### ISSUE TITLE
Is this project stalled

### ISSUE THREAD

**Issue by malix0** [cleidigh/EditEmailSubject-MX#15]
I'm interested on this project, but I don't see activity on this, just initial commit. I there a plan?

**Comment by RealRaven2000** [comment]
There is a plan - for discussion, join the bi-weekly Add-on Dev at 7:00pm GMT today (2pmEDT) - 

https://mozilla.zoom.us/j/676215741

**Comment by jobisoft** [comment]
We are still working on this.
