### ISSUE TITLE
Different/missing links to Home/Support on Add-ons page

### ISSUE THREAD

**Issue by goozak** [cleidigh/EditEmailSubject-MX#31]
On the Thunderbird site, the [French](https://addons.thunderbird.net/fr/thunderbird/addon/edit-email-subject/) version "Page d'accueil du module" link points here, but on the [English (US)](https://addons.thunderbird.net/en-US/thunderbird/addon/edit-email-subject/) page, [Add-on home page](https://addons.mozilla.org/en/firefox/addon/edit-email-subject/) is not working and [Support site](https://www.6admin.it/) points to some seemingly random website.

**Comment by jobisoft** [comment]
Fixed. Thanks for reporting this!
