### ISSUE TITLE
Star is lost when changing subject when Only local is unchecked

### ISSUE THREAD

**Issue by goozak** [cleidigh/EditEmailSubject-MX#32]
When editing the subject of a starred email, the star will be lost afterwards.

`Only local change` option is **unchecked** and my emails are POPed from the server.

Star is kept if `Only local change` is **checked**.

**Comment by jobisoft** [comment]
Fixed in https://github.com/cleidigh/EditEmailSubject-MX/commit/85fcc5ffaa72e269430df4e99646d6b5c3c746b5
