### ISSUE TITLE
Focus is lost when using right click menu

### ISSUE THREAD

**Issue by TigBuh99** [cleidigh/EditEmailSubject-MX#34]
In addition to the hotkey E issue that has already been reported, I would add that the right click menu option brings up the dialog to change the email subject, but the focus is lost and I usually have to try more than once to bring the change subject dialog back in focus.

(On Windows 10 Pro v.2004 OS Build 19041.450, laptop with external keyboard)

**Comment by jobisoft** [comment]
Dupe of #58
