### ISSUE TITLE
sunbject not changed

### ISSUE THREAD

**Issue by HarryHomers** [cleidigh/EditEmailSubject-MX#35]
hotkey "e" as said earlier doesn't work.
using right button to open the edit works but after changing some thing, completing with either the enter key or pushing the ok button, the window closes but nothing is changed on the email subject.

windows 10 pro version 2004,  os build 19041.508
tb v78.3.1 (32 bit)

**Comment by tidebre67** [comment]
strange, just tested. works with
windows 10 version 2004,  build 19041.508
tb v78.3.1 (64bit)

**Comment by HarryHomers** [comment]
I've done a few re-installs.
It worked every time until I added all my old emails back, it was working on new emails I used for testing.
Now all my emails (7.17GB) are back it only works with local changes not altering the emails them selves.
I have no other add ons install just this.
Is there a way of getting to alter the emails or is mine to big or many ?
I cannot find any where there is a log to see what is or is not happening.

**Comment by jobisoft** [comment]
i fixed something, can you check with the new version?

**Comment by HarryHomers** [comment]
no sorry not changing emails only thunderbird database, v4.3

**Comment by HarryHomers** [comment]
I don't know if this is related, I doubt it ?
![Capture](https://user-images.githubusercontent.com/11787138/94990476-4bbdb080-0574-11eb-89f4-dcba3adccdf8.PNG)
thats on a 2560x1440 screen

**Comment by jobisoft** [comment]
Could you check, if this still happens for your with version 6.2?
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2

**Comment by HarryHomers** [comment]
still no hoykey but that doesn't matter.
editing window opens as it should, thats fixed.

**Comment by jobisoft** [comment]
HotKey is SHIFT+CTRL+E (since 2020 / TB78). Single hotkeys are no longer supported by Thunderbird WebExtensions. You can adjust it in the Add-on Manager -> Gear Icon ->Manage Extension Shortcuts
