### ISSUE TITLE
Subject don't change if it contains iso char

### ISSUE THREAD

**Issue by Agostino-B** [cleidigh/EditEmailSubject-MX#37]
If the subject contains character as in RFC 2047, Edit Email MX start but don't change the subject.
An example of the subject with the trouble:

Subject:
 =?iso-8859-1?Q?SAQ_-_Gestion_de_la_qualit=E9_-_R=E9sultats_offre_de_produ?=
 =?iso-8859-1?Q?it_:_585422__?=
Thread-Topic:

**Comment by jobisoft** [comment]
Could you check, if this still happens for your with version 6.2?
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
