### ISSUE TITLE
EditEmailSubject-MX not in right click menu

### ISSUE THREAD

**Issue by dangnad** [cleidigh/EditEmailSubject-MX#39]
I recently updated Tb from version 60 to 78.3.3 and I am very very unhappy. Why does Mozilla continually alienate its loyal users? 

Of all the extensions permanently disabled by the new Tb only EditEmalSubject-MX remained and it is enabled. Except there is no "Edit Email Subject" in the right click menu of a message and hot key "E" does not work. 

Is there anything I can do. Remember Tools>Add-On Options is no longer there.

**Comment by dangnad** [comment]
Is there anyone on this forum? If so, would you please comment "hello" so I know that no one can solve my problem.

**Comment by jobisoft** [comment]
![grafik](https://user-images.githubusercontent.com/5830621/96967229-76fe4480-150f-11eb-872f-02e4d37a5c64.png)

![grafik](https://user-images.githubusercontent.com/5830621/96967317-9f863e80-150f-11eb-8a74-b342b39a7b38.png)

**Comment by jobisoft** [comment]
For me, on TB78.3.3 everything works.

**Comment by dangnad** [comment]
Thank you jobisoft. I uninstalled EditEmalSubject-MX, went to GitHub, downloaded v 3.2. ERROR, not compatible with Tb 78.3.3. I have Windows 10 v1903, Dell 8930. What's wrong. How can I get the same version as you that works on your machine?

**Comment by dangnad** [comment]
I installed EditEmailSubject-MX through Tb 78.3.3 and same story; your "Edit Email Subject" does not appear at the bottom of the right click menu. If I can't get this to work I'll have to go back to Tb v60 where it does work. I really don't want to do that.
I some how can attach an illustration of my right-click menu as it now stands. Well, imagine your illustration exactly as above but with the bottom line missing. Is there a setting in Tb I'm missing?

**Comment by dangnad** [comment]
I cannot edit the above comment. Why am I restricted here? 
Correction: "I somehow cannot attach an illustration..."

**Comment by cleidigh** [comment]
@dangnad 
the easiest way to attach an image in my opinion is to copy the image into the Paste buffer then  Paste into the message.  you can also drag and drop
usually you can edit your own messages I'm not sure why you were not able to
@cleidigh

**Comment by jobisoft** [comment]
I am using the official version on ATN:
https://addons.thunderbird.net/addon/edit-email-subject/

That works in TB78.

**Comment by tidebre67** [comment]
confirm version 4.3 works with TB 78.4 and Win 10/2004 except hotkey as mentioned in issue #33

**Comment by dangnad** [comment]
Trouble and sorrow. The version 4.3 still does not work with Tb 78.4. Help me please. There has to be a setting on your Tb that I have not set on mine.

Otherwise, it is back to Tb 60. I have used Tb for 22 years. I have developed a work flow using the subject line edit.

**Comment by jobisoft** [comment]
What error do you get? I just tested again in a fresh profile, so there is no special setting in my TB.

**Comment by dangnad** [comment]
I have said it before, there is no error message. "Edit Subject' is not in
the message right click menu.

**Comment by cleidigh** [comment]
I also can report a working 78.4/ Windows10
![image](https://user-images.githubusercontent.com/25272315/97118769-56d2af00-16e2-11eb-8e5b-2077c6655ce6.png)

**Comment by cleidigh** [comment]
@dangnad 
I think John is asking about the error console ( shiftControl J)
possibly also looking for conflicts with other extensions, have you tried disabling all others?

**Comment by dangnad** [comment]
That is very good for you but I posted because it doesn't work for me. I
will have to go back to v60 if I can't get it to work.

**Comment by cleidigh** [comment]
@dangnad 
did you check the air console
and/or disabled other extensions?
the fact that we have multiple working scenarios still indicates there are some difference

**Comment by dangnad** [comment]
C'mon, Christopher,  Mozilla made all extensions unworkable in v78. I only
have yours and Phoenicity.

**Comment by jobisoft** [comment]
@dangnad : Can you please post screenshots of the installed add-on in your add-on manager?
![grafik](https://user-images.githubusercontent.com/5830621/97118960-6b786c80-170d-11eb-9335-f0ce9e365971.png)

**Comment by jobisoft** [comment]
> C'mon, Christopher, Mozilla made all extensions unworkable in v78. I only have yours and Phoenicity.

We have about 40% of the top 100 add-ons ready for TB78. And constantly working on it.

**Comment by dangnad** [comment]
I can't paste or attach in this forum. As I told Chridtopher, I only have
one other exttension, Phoenicity.

**Comment by jobisoft** [comment]
Can you at least state that your add-on manager has an enabled Edit Email Subject MX entry, with the same icon as in my screenshot?

**Comment by cleidigh** [comment]
@dangnad 
did you try direct image Paste?
the point John and I making is that we have sufficient working examples beyond this extension and including this extension that we know we can make it work.  we just have to find the hidden issue
also getting you to the point where you can do image or file attachments here is important

**Comment by jobisoft** [comment]
Also, what is "Phoenicity" ? I cannot find an add-on with that name. Do you have a link?

**Comment by dangnad** [comment]
Well, v78 is no better than v60, cannot load attachments, sending this from
Gmail.

**Comment by dangnad** [comment]
Can't use Thunderbird to communicate with you. Have to send screenshots via
Web Gmail.

**Comment by jobisoft** [comment]
Just send me an email with the screenshot: 

john.bieling@gmx.de

**Comment by cleidigh** [comment]
@dangnad 
 does your issue entry look like my screenshot with the "Attach files..." footer?
![image](https://user-images.githubusercontent.com/25272315/97119386-43c1de00-16e6-11eb-91ba-0a14d78b9f25.png)

**Comment by jobisoft** [comment]
He is not using the github interface, but sends emails, which does not work.

**Comment by dangnad** [comment]
Here is my rt click menu

**Comment by jobisoft** [comment]
Please send me an ordinary email: john.bieling@gmx.de

**Comment by cleidigh** [comment]
just an idea:
if I am interpreting it correctly we went from 60=>78
and obviously the old extension was installed already
I wonder if something internally is still crossed
that could be eliminated by a fresh profile test like John did

**Comment by dangnad** [comment]
I was thinking about reinstalling. Sorry I must go now.

**Comment by cleidigh** [comment]
@dangnad 
is anything preventing you from using the gh web interface ?
this would make things a lot easier for you both for editing and attachments

**Comment by jobisoft** [comment]
I got screenshots from him, it looks correctly installed. We will have to ask him to setup a new profile. 

@dangnad : Reinstall is not needed

**Comment by dangnad** [comment]
Hello jobisoft
I have uninstalled Thunderbird and reinstalled a fresh version 78.4.0 with only necessary files copied over to the new profile. 
For editing the subject line of an email there is no change. I do not see Edit Email Subject in the right-click menu and 'E' does nothing. I have Windows 10 v1903 and Thunderbird 78.4.0 32 bit. What is wrong?

**Comment by jobisoft** [comment]
I have no idea. Instead of copying files into the new profile, please create a fresh empty one. If that does not work, I have absolutely no idea.

**Comment by TossOne53** [comment]
Hello, is this how MX is supposed to to work?  I can right click on an item in a folder and the menu looks correct:

![image](https://user-images.githubusercontent.com/47649663/103139340-68abe080-4698-11eb-87b6-c39df41fcaea.png)

If I am viewing that item and right click, I do not see Edit Email Subject:

![image](https://user-images.githubusercontent.com/47649663/103139385-d0fac200-4698-11eb-9d12-83a21d37574a.png)

Sorry for the user-type question but thought it may help.

**Comment by jobisoft** [comment]
This is intended, we only added the menu entry to the context menu of the message list.

**Comment by dangnad** [comment]
Why are you emailing me at this late date? EditEmailSubject does NOT work
in Thunderbird 78. It only works on your PC, John. If you want to be in the
software business then you have to write your applications for everyone and
every browser.

You gave yourself away last Nov 11th when you said "I have absolutely no
idea [why it won't work on your machine]".That means you should get a
different day job.

I solved the problem nearly two months ago by uninstalling Tb 78 and
reinstalling Tb 60. EES works there.

**Comment by TossOne53** [comment]
> 
> 
> This is intended, we only added the menu entry to the context menu of the message list.

Makes perfect sense, thank you.  Would it be possible that, while the E hotkey is not working, to add Edit Email Subject to the context menu when viewing the message?

**Comment by RealRaven2000** [comment]
> Why are you emailing me at this late date? EditEmailSubject does NOT work in Thunderbird 78. It only works on your PC, John. If you want to be in the software business then you have to write your applications for everyone and every browser. You gave yourself away last Nov 11th when you said "I have absolutely no idea [why it won't work on your machine]". That means you should get a different day job. 

This is not how it works. For individual machine support there is 3rd level or 2nd level support in commercial software. And it's costly (e.g;. 80$ just to open a case with Microsoft) - no software vendor guarantees software working on every machine, if you break your profile then it is on you and individual unpaid help is not something you can just demand from the developers - they have to work on features and documentation. 

And if you want to help solve a bug on github then you need to give the information there (go on the website) - because sending an email will not transmit any of your screenshots.
