### ISSUE TITLE
access Option, where is it?

### ISSUE THREAD

**Issue by gabri25ele** [cleidigh/EditEmailSubject-MX#41]
I red 
To access Option, since Thunderbird 60:
1- Right click to enable Menu bar
2- Menu "Tools > Add-on Options > EditEmailSubject"
3- Check/uncheck checkbox

but... in Tools > Add-on Options I didn't see any EditEmailSubject item.
I am on Thunderbird 78.6.0

**Comment by jobisoft** [comment]
Options are in the add-on manager behind the "..." (3-dot) button, either behind "Options". We will get a dedicated options button in the add-on manager soon.

![grafik](https://user-images.githubusercontent.com/5830621/102985938-46875680-4510-11eb-8d56-5a6c644895ef.png)

**Comment by gabri25ele** [comment]
ok, need to go in addon page.
thanks
