### ISSUE TITLE
doubling `Edit Mail Subject` in context menu

### ISSUE THREAD

**Issue by kanlukasz** [cleidigh/EditEmailSubject-MX#44]
### Issue: 
The menu item appears twice 
![obraz](https://user-images.githubusercontent.com/30685349/106583826-cbb94e80-6545-11eb-84fe-ab8cccd636ba.png)

### Tb Version:
78.7.0 (64-bit)
### OS:
 Windows 10 20H2

**Comment by jobisoft** [comment]
Should be fixed, have not seen it for a long time.
