### ISSUE TITLE
No access to option via the main menu

### ISSUE THREAD

**Issue by rakoczy** [cleidigh/EditEmailSubject-MX#47]
When trying to change the option (according to the instruction on the extension description) you enter the sequence Menu > Tools >Add-On Options it's impossible to select EditEmailSubject MX as it doesn't show.
However, it is possible to reach the option selecting Option in the three-dot menu on the extension description page. 
Thus both - the description and the extension interface - should be corrected.
Thunderbird 78.7.1
Windows 7

**Comment by jobisoft** [comment]
Removed the wrong description.
