### ISSUE TITLE
Default settings lead to apparently "not working" config

### ISSUE THREAD

**Issue by rakoczy** [cleidigh/EditEmailSubject-MX#48]
Just after installation, the option is set to global modification of the mail subject, but this leads to no change of displayed subject content. Apparently, there's no change to the local copy of the subject line. 

IMO the option implementation breaks the logic of the extension: if I want to make any change to the subject I want to be able to see it in the Thunderbird. Thus the local Thunderbird index database should be modified **always** while the option should rule the modification of the email. Also, the displayed subject line should always be in agreement with email content.

Currently, when the subject was changed while the option was set and then the option was reset to the initial state (off) the displayed subject line is shown in the original version, while an attempt to edit it shows the previously modified version in the editing window. That suggests that the real subject is different than the displayed one (what should be true of course but what also may be confusing as someone can forget about previously applied changes). The option shouldn't change the way the subject lines modified earlier are displayed.

**Comment by jobisoft** [comment]
I dropped support of local mode:
https://github.com/cleidigh/EditEmailSubject-MX/commit/97d8950a39548b5735d5fb244f40c86da0906638

**Comment by jobisoft** [comment]
Please switch to v6.2, which introduced a backup option, to make sure no email is lost (there are such reports, v6.2 does fix something in that area)
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
