### ISSUE TITLE
[TB-78.7.1] IMAP Subject editing leads to date problems

### ISSUE THREAD

**Issue by erricodavide** [cleidigh/EditEmailSubject-MX#49]
Hi!

I've been using your tool in IMAP mode with Gmail for quite a long time and had no problems until updating to Thunderbird 78.7.1. 

From this version on, when I edit a subject, the message gets appended with current date instead of its header date.
Thunderbird continues showing the correct date (the header one) and behaves accordingly, but Gmail app/webapp show the message as if it arrived at the time of subject editing process.
This discrepancy between TB and Gmail app/webapp makes your tool unusable for my purposes.

I genuinely think I'm not the only one facing this problem.
Also, updating TB to 78.8.1 doesn't solve the issue.

Any clue?

Thank you in advance.

**Comment by jobisoft** [comment]
Could you check, if this still happens for your with version 6.2?
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2

**Comment by erricodavide** [comment]
> Could you check, if this still happens for your with version 6.2? https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2

I just checked. Unfortunately, the issue is still there.

**Comment by jobisoft** [comment]
Please try v7.0:
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v7.0

Does that fix your issue?

**Comment by erricodavide** [comment]
> Please try v7.1: https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v7.1
> 
> Does that fix your issue?
> 
> Edit: Released v7.1

Just tried v7.1, I'm not able to make it work. The extension hangs after clicking "OK" (the "loading" GIF never stops spinning). This happens both selecting "backup to EES-Temp" and not selecting it. I tried in a folder with only 4 messages as well as in my true inbox folder.

**Comment by jobisoft** [comment]
Do you see the new/renamed email in the temp folder?

**Comment by erricodavide** [comment]
No, the EES-Temp folder remains empty and the subject doesn't change.

**Comment by jobisoft** [comment]
OK, that is why it does not work, it is not able to save the temp file to the local folder (that is step one, step two is moving it to the actual folder, step three is delete or backup of original mesage). Do you see an error on the error console?

**Comment by erricodavide** [comment]
Yes. 
TypeError: messenger.messages.import is not a function        ([editemailsubject.mjs:127:47])

**Comment by jobisoft** [comment]
Ah, you need Thunderbird Beta. And I have to raise the min supported version from 102 to 115.

**Comment by jobisoft** [comment]
Or wait till next week, when Thunderbird 115 is officially replacing 102.

**Comment by jobisoft** [comment]
I released v7.2, which can only be installed in Thunderbird 115+
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v7.2

**Comment by erricodavide** [comment]
> I released v7.2, which can only be installed in Thunderbird 115+ https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v7.2

I installed Thunderbird 115 Beta and YES! It works! 
Plus, the message date in Gmail app/webapp is preserved. 

To be honest, so much time has passed since I first opened this issue, that I had lost hope for an answer and was wondering what happened to the project... but better late than never! From now on, I will be happy to be using EES again! Thank you very much!

**Comment by jobisoft** [comment]
Due to the yearly release, we tend to work on our add-ons only during this one time in the year, before the next release. It is a very bad habbit. I am glad this is fixed now.

Did you upgrade your existing "real" Thunderbird profile and use it now in Thunderbird Beta 115, or did you create a fresh one for Beta? If you upgraded your "real" profile, be sure to disable automatic updates for your Beta installation, so it does not update to 116 next week, because then you cannot use that profile in Thunderbird 115 ESR anymore. 

I do not suggest to follow the downgrade tutorials available online, instead try to not upgrade to 116 in the first place. Feel free to ping me if you have questions regarding this.

**Comment by erricodavide** [comment]
I created a fresh profile just for the beta. Actually, I did this just to test EES. I then uninstalled the beta and I am going to wait until TB 115 comes out as an official upgrade, then I'll install EES again. 
Thank you for your help and suggestions.
