### ISSUE TITLE
Poll: Conversion Log  method

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/EditEmailSubject-MX#5]
All
I am not sure the absolute best way to track/document our progress , but a permanent issue is easy.
I was thinking of tracking the basic steps here with the following approach:
Create a markdown checkbox for each item with the paragraph explanation (mainly what we did NOT why we did it) after the explanation issue pointers to the discussion part , examples, documentation et cetera.  Again just my idea.  I will create the first two example items repository, jar.

#
Conversion Log Example:

[x] Repository baseline

- created conversion extension repository structure including utility folders
- Loaded original source With extension source/xpi
- original tag v2.1.1

# 
[x] Jar extension structure - removed for simplicity/unnecessary redundancy

Many extensions have used a compressed jar file for the extension content.

References/Issues:
Jar removal #1 
Article on xpi & jar compression, transition
 https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/4/Updating_extensions_for_Firefox_4#XPI_unpacking
why this is unnecessary now.  

- Removing the jar requirements removing the jar references in chrome.manifest and
  the reference to packing in the install file.  MailExtensions will not use the jar approach
- Create non-jar extension baseline tag v2.1.2b1 
- This loads and executes within Thunderbird 60.9.1

#
[ ] Next source step manifest file?  Still hybrid for testing

**Comment by eyalroz** [comment]
I'd say use a "permanent issue" like you suggest + issue for each conversion step, linked to from the log. Possibly - make the title of each item hold the link to the specific issue.

**Comment by opto** [comment]
yes, it would be good to have separate issues for separate tasks. So for example one issue for jar conversion, another for manifest creation.

And maybe a meta issue where we order stuff (jar conversion before manifest, etc)

**Comment by jobisoft** [comment]
I would like to pick this issue up again. I just merged the changes for TB68 and created a new release. What do you guys think about using the release page as the final curated log?

See here (step 1 and step 2):
https://github.com/cleidigh/EditEmailSubject-MX/releases

Another option would be to create a dedicated wiki page which acts as an update log.

This would seperate the "discussion" part in the issue section from the final result. If an issue includes important information, we can either link to it from the release page or clone the relevant information into the release notes.

As you may notice, I manually placed the relevant commit links into the release notes but actually used the compare mechanism to "merge" the two commits for the jar update into one diff. I like it like that, as you can see "what goes out and what goes in" in one go and i wanted to show how this can be done. But we can of course change that and list both commits individually.

What do you think?

What do you think?

**Comment by RealRaven2000** [comment]
I think using the release page is good, but can we simply use version numbers as 
titles? Something of the form major.minor would be ideal. You can actually  add a 
functioning build (xpi) to each of these for trying out.

Axel

*Axel Grude <mailto:axel.grude@gmail.com>*
Music Production and Composition
Thunderbird Add-ons Developer (QuickFolders 
<https://addons.thunderbird.net/thunderbird/addon/quickfolders-tabbed-folders/>, 
quickFilters <https://addons.thunderbird.net/thunderbird/addon/quickfilters/>, 
QuickPasswords <https://addons.mozilla.org/firefox/addon/quickpasswords/>, Zombie Keys 
<https://addons.thunderbird.net/thunderbird/addon/zombie-keys/>, SmartTemplate⁴ 
<https://addons.thunderbird.net/thunderbird/addon/smarttemplate4/>)
Visit my YouTube Channel <https://www.youtube.com/c/thunderbirddaily> for email 
productivity tips Get Thunderbird!

**Comment by RealRaven2000** [comment]
I like releases, but can we use simple version numbers (I suggest major.minor, such as 3.1) you can also attach a binary build (xpi) to each release for testing,

**Comment by jobisoft** [comment]
During the call from 24.03. we decided to log the changes in the wiki inside the doc draft for DTN, which will move to DTN after everything is done.

The release page will have links to the changes/wiki, but it will be a normal release page again.
