### ISSUE TITLE
Extend functionality to be able to edit more headers (like HeaderTools Lite)

### ISSUE THREAD

**Issue by Johann-Tree** [cleidigh/EditEmailSubject-MX#51]
Since https://addons.thunderbird.net/thunderbird/addon/headertools-lite/ is not working anymore with Thunderbird 78 I'm looking for alternatives to edit especially the References-header and stumbled upon this AddOn.

Is there any chance that this extension could be extended to add the ability to edit other headers apart from subject?

Very often I have to add a References-header because many smartphone apps use neither References nor In-Reply-To.
(I have my sent e-mails also in the Inbox and use View -> Sort by -> Threaded.)

The ability to edit the full message source would be great but is not as important to me. I use it for example mostly to repair wrong X-Mozilla-External-Attachment-URL entries after detaching attachments.

**Comment by jobisoft** [comment]
> to repair wrong X-Mozilla-External-Attachment-URL entries after detaching attachments

Could you file a bug for that so it gets fixed in TB?

The other request is currently not possible, will look into it once needed WebExtension APIs have been added.

**Comment by Johann-Tree** [comment]
> > to repair wrong X-Mozilla-External-Attachment-URL entries after detaching attachments
> 
> Could you file a bug for that so it gets fixed in TB?

The bug was filed 15 years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=350825



 
> The other request is currently not possible, will look into it once needed WebExtension APIs have been added.

Do you mean editing other headers or editing full source - or both?

**Comment by jobisoft** [comment]
HeaderTools lite seems to be still maintained.

**Comment by Johann-Tree** [comment]
Also there ist https://addons.thunderbird.net/de/thunderbird/addon/header-tools-improved/ now
