### ISSUE TITLE
Subject not changed when folder name contains special character "+"

### ISSUE THREAD

**Issue by TossOne53** [cleidigh/EditEmailSubject-MX#52]
This could be related to #37 but I cannot be sure.

I edit the subject of a message in any of these folders and the subject is not updated:

![2021-07-22_10-20-52](https://user-images.githubusercontent.com/47649663/126681733-86374d13-5bc8-45e2-acac-a3041a876ec7.png)

Updates to subjects in other folders works fine.  I believe the "+" in the folder name is the difference.

Win10 Home 21H1    Tbird 78.12.0 32 bit

**Comment by TossOne53** [comment]
This still is a problem.  My Tbird is now 91.3.1 and EditEmailSubject MX is 5.1.  Is there any response to this issue that was first identified in July, 2021?  Thank you.

**Comment by jobisoft** [comment]
Let us hope for 91.4.

**Comment by DGrothe-PhD** [comment]
Works with my TB 102.7.2 (32-Bit) and EditEmailSubject 6.1.
![EditEMailSubjectMX_Issue52_PlusInFolderName](https://user-images.githubusercontent.com/64636863/218323618-227e0648-146c-4b69-9e2f-f06a84da9f77.png)

**Comment by TossOne53** [comment]
Also now working for me, the OP, using TB 102.7.2 64 bit and EditEmailSubject MX 6.1.  I believe this can be closed as it is working fine for me now.  Thank you.
