### ISSUE TITLE
Stopped working - TBird 91.0.2

### ISSUE THREAD

**Issue by exapplerep** [cleidigh/EditEmailSubject-MX#54]
Upgraded to TBird v91.0.1. The Add-On stopped working. It still shows in the contextual menu but altering the subject doesn't work. I have the checkbox for "local changes only" UNchecked. I uninstalled then re-installed the latest version (4.3). Quit and then re-launched TBird. Same issue.

**Comment by jobisoft** [comment]
https://github.com/cleidigh/EditEmailSubject-MX/issues/53

**Comment by exapplerep** [comment]
I see links to source code but where might I find the compiled Add-On? Thanks. :D

**Comment by jobisoft** [comment]
It is now avail on ATN:
https://addons.thunderbird.net/thunderbird/downloads/file/1019486/edit_email_subject_ees-5.1-tb.xpi

**Comment by exapplerep** [comment]
Thanks so much. Working perfectly.
