### ISSUE TITLE
Edit subject: add autofocus for input field?

### ISSUE THREAD

**Issue by user908348** [cleidigh/EditEmailSubject-MX#58]
When I edit the subject line I first have to click in the input field to start editing, can't this be done automatically by adding `autofocus` to the input code:

https://github.com/cleidigh/EditEmailSubject-MX/blob/a58d4cac616e52ee2ead0b49a586c5b8e4a8cf85/src/content/editemailsubjectPopup.html#L13

`    <input style="flex-grow:1;" type="text" id="editemailsubjectInput" autofocus/>`

**Comment by TossOne53** [comment]
Hello, a previous version did just this!  (Maybe two years ago.)  I also would like (the option of(?)) this feature.

**Comment by jobisoft** [comment]
autofocus didn't do it, but focusing the field + window did the trick.
