### ISSUE TITLE
Thread integrity lost when using EditEmailSubject MX

### ISSUE THREAD

**Issue by DwainWilder** [cleidigh/EditEmailSubject-MX#60]
When using EditEmailSubject MX to change subject line, the email is no longer the parent of its own thread. So answers to the email appear on a different thread, with no apparent way to establish the renamed message as the thread parent. 

I use threads to order conversations in important ways, so this loss is significant

![TestingEditEmailSubject MX Thread Integrity](https://user-images.githubusercontent.com/111071375/184166976-c9e10215-737a-4746-9eb5-611d475c5745.png)
.

**Comment by DGrothe-PhD** [comment]
Just tested it with version 6.1 on TB 102.7.1 (Windows 8.1 x64) and could not reproduce this issue. With or without sorting as grouped by threads it works fine.
Tested:
1) added a text to the subject of thread parent
2) added text to subject of thread child
3) first forwarding an e-mail, then added a text to subject of original e-mail
4) forwarded an e-mail after having edited the subject
![EditEmailSubMXIssue60](https://user-images.githubusercontent.com/64636863/216834235-0981dacc-026e-417d-a818-f8374251698e.JPG)

**Comment by jobisoft** [comment]
Could you check, if this still happens for your with version 6.2?
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
