### ISSUE TITLE
Thundbird update request

### ISSUE THREAD

**Issue by Jaylo70** [cleidigh/EditEmailSubject-MX#63]
Hi!
Everytime I open Thunderbird there is a pop-up saying that there is a new version available. When I click on the pop-up, the update ends up being the same version that I already have. So there is no new update.
My version is 102.3.3. It says that it is up to date already.

**Comment by Jaylo70** [comment]
![Thunderbird download request](https://user-images.githubusercontent.com/110245114/196644893-a2422f3b-ebfd-4c27-bd2d-ca8b9873e490.png)

**Comment by jobisoft** [comment]
What does this have to do with EditEmailSubject?

**Comment by Jaylo70** [comment]
I clicked on new issue. So it brought me here.
Ok thanks

**Comment by jobisoft** [comment]
Closing this as invalid.
