### ISSUE TITLE
Change the subject, no funktion

### ISSUE THREAD

**Issue by christianwestphal75** [cleidigh/EditEmailSubject-MX#66]
Hello,
I've been using the addon for a long time.

On my Macbook Pro M1, Monetrey, Thunderbird 102.5.0
it doesn't work anymore
I change the subject, hit enter > nothing happens

I don't know how long the problem has existed, but it has been for a while.

Mail account IMAP

Anyone a solution?

**Comment by jobisoft** [comment]
Dublicate of #35
