### ISSUE TITLE
Does not support Hebrew subject changes, when working in header change mode

### ISSUE THREAD

**Issue by Erez-R2D2** [cleidigh/EditEmailSubject-MX#68]
I guess it is a Unicode issue.
You are our only hope OB wan.

**Comment by jobisoft** [comment]
Fixed in https://github.com/cleidigh/EditEmailSubject-MX/commit/85fcc5ffaa72e269430df4e99646d6b5c3c746b5

**Comment by jobisoft** [comment]
Please switch to v6.2, which introduced a backup option, to make sure no email is lost (there are such reports, v6.2 does fix something in that area)
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
