### ISSUE TITLE
Strategy to replace flex xul layout

### ISSUE THREAD

**Issue by jobisoft** [cleidigh/EditEmailSubject-MX#7]
Is this something we should cover?

I used the flex attribute of xul elements to style my UI. I think we can replace that with the css flexbox.

https://weblog.west-wind.com/posts/2017/nov/11/flexing-your-html-layout-muscles-with-flexbox

I have not yet managed to get a html:textarea to flex in height, it is always bound the the "rows" attribute. I know the current project does not have a lot of UI, but I wanted to log that as I think it will be important. 

What do you think?

**Comment by cleidigh** [comment]
Absolutely, I have been dealing with this and other similar issues and wanting to write about it.
I've also had several great discussions with Alessandro.
This affects everyone and showing people how to transition and when will be very important.
I assume I have plenty to speak about and show about HTML flex and other similar things.

**Comment by neandr** [comment]
This page was very helpful for me:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/
