### ISSUE TITLE
Question: Difference between 'EditEmailSubject' and 'EditEmailSubject MX'?

### ISSUE THREAD

**Issue by SILENT-da** [cleidigh/EditEmailSubject-MX#73]
In the description of this addon here are written the following reasons for creating this project:

_"MailExtension Conversion Project_
_- updating the code to be a "pure" MailExtension_
_- desired goal of providing detailed process, tips and conversion notes_
_- helping developers with the transition process"_

But honestly, i don't understand it.

What is the difference between the original project and this one? Could someone explain this to me (as a non-programmer)?
What are the advantages (for an enduser) of using the 'MX'-version?

Once i (a german enduser) decided to use this addon, but i can't remember why anymore. Quite possible, the original version didn't work correctly on my system and someone gave me the recommendation to try this.

Anyway, thanks a lot for that!

**Comment by jobisoft** [comment]
The original add-on was not updated to be compatible with TB78 (I think) and we wanted to update it. I do not fully remember the situation back then, but I think we were not able to reach the original developer, to let us update the original add-on, so we forked it and made it our version (this repository) compatible again. In the beginning we were a group of multiple add-on developers who used this rather simple add-on to learn how the new style of add-on programming works (WebExtensions or MailExtensions = MX) and we discussed it for multiple months in the official add-on developer zoom meetings. It is now mostly maintained by me. In the next version I will be able to fully convert it to a pure WebExtension.
