### ISSUE TITLE
Empty subject - nothing happens

### ISSUE THREAD

**Issue by dezertdezine** [cleidigh/EditEmailSubject-MX#75]
Windows 10
Thunderbird 102.12.0
EditEmailSubject MX 6.2

I have been sent an email with an attachment but with no subject.
Right-click email in message list > select Edit Email Subject.
Nothing happens.

Seems to working ok with other emails.

**Comment by jobisoft** [comment]
Please try v7.0:
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v7.0

Does that fix your issue?

**Comment by dezertdezine** [comment]
Thanks for looking at this issue and the quick response. I installed v7.1, unfortunately it doesn't quite fix it, now an empty dialog box opens, but that's all. 

![image](https://github.com/cleidigh/EditEmailSubject-MX/assets/1206084/8f74d7c5-fb17-42ef-bb0f-7d9890bf6588)

**Comment by jobisoft** [comment]
Huh, because it does not find the subject header and throws an out of bounds error. Will investigate

**Comment by jobisoft** [comment]
I am confident, that this is now fixed in v7.2:
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v7.2

Could you try it out?

**Comment by jobisoft** [comment]
The fix is in the version for TB 115 only.

**Comment by Katermerlin** [comment]
Do you intend to fix it also for 102 versions?

**Comment by jobisoft** [comment]
To be precise: It is now a pure WebExtension and no longer needs the "full access to your computer" permission.

**Comment by jobisoft** [comment]
> Is there anather way to change an empty subject fiield...?

Not in 102, not with my add-on.

> ...I'm not sure if I should update to V. 115... Because I experienced a desaster with an early Version of 102 which damaged my mail database and I am happy that everything runs smoothly at the moment with V 102.9.0 ...

Official role-out of TB115 has not started yet. You can download it and try it with a new profile, but automatic updates are not enabled yet. Overall, release quality of TB115 is better than compared to TB102

**Comment by dezertdezine** [comment]
At last I now have Thunderbird 115 running and can report that the this issue is now resolved for me. 

Thanks for this great/useful extension.
