### ISSUE TITLE
Manually sort folders

### ISSUE THREAD

**Issue by Jaylo70** [cleidigh/EditEmailSubject-MX#76]
With the new version of Thunderbird, the manual sort add-on I had is not compatible.  

Is there another addon that exists?  Or is there a way to manually sort folders?  Or do you intend on adding this as an option to Thunderbird?

Thanks

**Comment by jobisoft** [comment]
https://github.com/protz/Manually-Sort-Folders/pull/201

**Comment by Jaylo70** [comment]
So do I understand that it would work...

Can you indicate the steps keeping in mind that I am not a web technician?

**Comment by Jaylo70** [comment]
ok I was able to add the add-on.  Thanks
