### ISSUE TITLE
Manual sort not working correctly

### ISSUE THREAD

**Issue by Jaylo70** [cleidigh/EditEmailSubject-MX#77]
The option to move the folders manually is not working.  The window panel with folders does not appear.
![View panel with folders missing](https://github.com/cleidigh/EditEmailSubject-MX/assets/110245114/eebb7a18-67ba-4f42-a23e-c115d6e7d4df)

_Originally posted by @Jaylo70 in https://github.com/cleidigh/EditEmailSubject-MX/issues/76#issuecomment-1665800008_

**Comment by jobisoft** [comment]
@Jaylo70 : I would like to make you aware, that you are posting on the wrong page. This is the issue section of the Edit Email Subject add-on, not affiliated with manual sort folders.

You are not using the latest beta release of manual sort folders, which is here:
https://github.com/protz/Manually-Sort-Folders/files/12089722/Manually-Sort-Folders-v3.2.zip

I will close this issue now. If you have further questions regarding Manual Sort Folders, please post there:
https://github.com/protz/Manually-Sort-Folders/issues
