### ISSUE TITLE
Cannot change subject when subject does not begin the a space

### ISSUE THREAD

**Issue by pdcweb** [cleidigh/EditEmailSubject-MX#86]
For some time now I have found I cannot change the subject randomly.
Today I narrowed the issue down.
In this example, I want to remove the SPAM tag from the subject...

This subject line cannot be changed:
Subject:*****SPAM***** Can I change the subject line?

This subject line can be changed:
Subject: *****SPAM***** Can I change the subject line?

It looks like the current version of Spam Assassin on our server isn't properly inserting the space after the colon.
I have updated the SA config to use " *****SPAM*****" instead of "*****SPAM*****" to tag subjects.

Hopefully this SA change fixes the issue for me BUT maybe EditEmailSubject-MX should be updated to not look for the space after the colon and some of the random "can't change subject" issues might be solved?

**Comment by jobisoft** [comment]
Whoo. Interesting. Your observation is of course absolutely correct:
https://github.com/cleidigh/EditEmailSubject-MX/blob/master/src/content/scripts/editemailsubject.mjs#L57

**Comment by jobisoft** [comment]
Could you check if 7.5 is fixing this for you and does not introduce other issues in the "normal" case (where the space is present)?

[EES_7.5.zip](https://github.com/user-attachments/files/16739555/EES_7.5.zip)

Do not unpack this file, but just drag the link into Thunderbirds add-on manager tab.

**Comment by pdcweb** [comment]
EES 7.4 has been working correctly for me for some time now.

I was not able to install EES 7.5 as requested as I get a "not compatible with TB 115.14.0 message.
