### ISSUE TITLE
V7.2 gives "not compatible with v. 128.1.1" when I try to install

### ISSUE THREAD

**Issue by Llaves** [cleidigh/EditEmailSubject-MX#87]
I downloaded the v7.2 xpi file, which I believe is the latest version. When I try to install from the file I get an error that it is not compatible with v 128.1.1

**Comment by jobisoft** [comment]
The most recent version is v7.4:
https://addons.thunderbird.net/addon/edit-email-subject/

ATN (addons.thundebird.net) is the only authentic platform to download add-ons. However, users should not have to download XPI files at all, but just open the Add-on Manager in Thunderbird, search for an add-on and select "Add to Thunderbird".

![image](https://github.com/user-attachments/assets/6d5cf024-a8cb-4f4f-9306-de1cded0fe50)
